Made the database for project class. Made activity class. Data is bei…
C-Training/CustomDatabase pull request #22
Opened 2021-01-25 21:29 UTC by TalhaAsjad

…ng inserted at head and tail, deleted from head and tail and being displayed.

2021-01-26 01:11 UTC, haseebuchiha approved these changes

2021-01-27 20:32 UTC, ParanoidBat commented on CustomeDB/Activity.cpp
> +void Activity::setData(string name, int id, string description, int client_id, int money_earned, string deadline, string complete_date) {
setData is an ambiguous function name. specify in name, what class are you setting data for. like: setDataProject. Likewise there are functions in other places that have same issue

2021-01-27 20:32 UTC, ParanoidBat commented on CustomeDB/Activity.cpp
> +void Activity::setData(string name, int id, string description, int client_id, int money_earned, string deadline, string complete_date) {
plus. change money_earned type to string. in its respective class as well and any other places such setter/getter

2021-01-27 20:32 UTC, ParanoidBat commented on CustomeDB/LinkedList.cpp
> +        prjtail = temp;
why are both the iterator(prjtail) and its next pointing to same object? and why isn't temp's next NULL ?

2021-01-31 05:06 UTC, haseebuchiha commented on CustomeDB/CustomeDB.cpp
> +    //test.deleteHeadProjectDatabase();
Why is there code in main file???

2021-01-31 05:07 UTC, haseebuchiha commented on CustomeDB/LinkedList.cpp
> +            cout << "This id is not present in database. \n";
Why did you add code for input directly inside linkedlist class??? If you want to handle input you can handle it inside Activity class only

2021-01-31 05:08 UTC, haseebuchiha commented on CustomeDB/LinkedList.cpp
> +//}
Remove the comments

2021-01-31 05:08 UTC, haseebuchiha commented on CustomeDB/LinkedList.cpp
> +//}
Remove the comments

2021-01-31 05:08 UTC, haseebuchiha commented on CustomeDB/LinkedList.cpp
> +//}
Remove the comments

2021-01-31 05:09 UTC, haseebuchiha commented on CustomeDB/LinkedList.h
> +    //size_t listSize();
Remove comments

2021-01-31 05:09 UTC, haseebuchiha commented on CustomeDB/LinkedList.cpp
> +
Remove Comments

2021-01-31 05:10 UTC, haseebuchiha commented on CustomeDB/LinkedList.cpp
> +//}
Remove Comments

2021-01-31 05:10 UTC, haseebuchiha commented on CustomeDB/LinkedList.cpp
> +
Remove Comments

2021-01-31 05:10 UTC, haseebuchiha requested changes
Fix all the commented changes

2021-02-02 12:36 UTC, merged