L
C-Training/CustomDatabase pull request #3
Opened 2021-01-05 13:40 UTC by hamzafj5

2021-01-05 17:05 UTC, haseebuchiha requested changes
No update for link list

2021-01-08 19:30 UTC, Mimi848 requested changes
for(int i = 0; i < 10000000 ; i++){
        l1.addAtEnd(1, "talha", 20);
        l1.addAtEnd(2, "haseed", 10);
        l1.addAtEnd(3, "bats", 25);
        l1.deleteAtHead();
        l1.deleteAtHead();
        l1.deleteAtHead();
        
    }

2021-01-08 19:30 UTC, Mimi848 commented on CustomeDB/CustomeDB.cpp
> +struct Node {
there is memory leakage in your program. i want u to find it out. for hint run add data and delete at head hundreds of thousands of time try testing it.

2021-01-13 21:09 UTC, haseebuchiha requested changes
Same issues as talha. Definitions should be written in class.cpp files

2021-01-24 05:53 UTC, closed without merging